language: python
python:
  - "2.7"
  - "2.6"
env:
 - DJANGO=1.4
 - DJANGO=1.5
install:
 - pip install -q Django==$DJANGO --use-mirrors 
 - pip install pep8 --use-mirrors
 - pip install https://github.com/dcramer/pyflakes/tarball/master
 - pip install mock --use-mirrors
 - pip install django-auth-ldap --use-mirrors
 - pip install netaddr --use-mirrors
before_script:
 - echo "secret" > django_project/ldap-password
 - python manage.py syncdb --noinput
 - "pep8 --exclude=migrations --ignore=E501,E225 fwadmin"
 - pyflakes -x W fwadmin
script:  python manage.py test fwadmin
