- hosts: servers
  sudo: true
  vars_files:
    - vars.yml 
    - vars_pkgs.yml 
    - vars_derived.yml

  tasks:
  # packages
  - name: Install python-apt (manually) as the "apt" ansible module needs it
    shell: apt-get install -y python-apt python-software-properties
  # node (for bower)
  - name: add nodejs PPA
    apt_repository: repo=ppa:chris-lea/node.js
  - name: apt update
    apt: update_cache=yes
  - name: Install apt packages
    apt: pkg=${item} state=installed update-cache=yes
    with_items: ${apt_packages}

  # app setup
  - name: create app user
    user: name=${project_user} home=${project_root}
  - name: create application dir
    file: group=${project_user} owner=${project_user} mode=755 state=directory
          path=${item}
    with_items:
      - ${project_root}
      - ${project_root}/application
      - ${project_root}/django_project
      - ${project_root}/public_html

  # copy ssl keys
  - name: copy ssl chain
    copy: src="non-git-files/${project_server_fqdn}/${project_ssl_cert_chain}"
          dest="/etc/ssl/"
    tags: ssl
  - name: copy public key
    copy: src="non-git-files/${project_server_fqdn}/server.crt"
          dest="/etc/ssl/${project_server_name}.pem"
    tags: ssl
  - name: copy private key
    copy: src="non-git-files/${project_server_fqdn}/server.key"
          dest="/etc/ssl/private/${project_server_name}.key"
    tags: ssl

  # apache setup
  - name: add apache vhost
    template: owner=root mode=0644 src=templates/apache2-site 
              dest=/etc/apache2/sites-enabled/${project_name}
    notify: reload apache2
  - name: add ssl-ports.conf
    template: owner=root mode=0644 src=templates/ssl-sni.conf
              dest=/etc/apache2/conf.d
    notify: reload apache2
  - name: enable apache ssl
    shell: a2enmod ssl
    notify: reload apache2

  # create DB
  - name: create database "${project_db_name}" db
    postgresql_db: db=${project_db_name}
    sudo_user: postgres
    tags: db
  - name: create db user "${project_db_user}"
    postgresql_user: db=${project_db_name} 
                     user=${project_db_user}
                     password=${item}
                     priv=ALL
    with_file:
      - "non-git-files/${inventory_hostname}.db-password"
    sudo_user: postgres
    tags: db
  # and set the db file in django
  - name: create db-password
    copy: src=non-git-files/${inventory_hostname}.db-password
          dest=${project_root}/application/django_project/db-password
    tags: db

  # include handlers
  handlers:
    - include: handlers.yml

# do the deploy
- include: deploy.yml

